name: Deploy Flask API to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "Dockerfile,durian_classifier.onnx,durian_classifier_app.py,requirements.txt"
        target: "~/DURIAN_CLASSIFIER_PROJECT"  # Folder on EC2 where app will live

    - name: SSH into EC2 and deploy Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop durianclassifierapi || true
          docker rm durianclassifierapi || true
          docker pull thomasibudiman/durian-classifier:v5
          docker run -d -p 80:5000 \
            --name durianclassifierapi \
            --cpus="0.5" \
            thomasibudiman/durian-classifier:v5
